<h1>Cerita saya selama mengikuti Pemrograman Web</h1>
<hr>
<p>Selama mengikuti Pemrograman Web yang diajar pak sofyan saya mendapatkan banyak pembelajaran dan pengetahuan yang baru seperti dalam hal coding, membuat css dan sebagainya.Kadang pak sofyan juga mengajar seperti kadang membuat lucu agar kelas tidak terasa bosan dan agar kami smua yang di dalam kelas tidak terlalu tegang dengan pelajaran yang diberikan atau yang diterangkan.</p>
<p>Dalam pemrograman web ada coding tapi coding yang diberikan tidak terlalu sulit tapi mudah diingat dan mudah ditahu, di halaman web yang diberikan juga yang menjadi tugas dapat juga mengubah atau menmbahkan seperti membuat css untuk menambah background, mengubah warnanya dan sebagainya itu semua untuk membuat halaman web tersebut lebih menarik dan lebih enak dipandang atau sesuai dengan yang diinginkan dan dapat juga untuk mengubah tulisan atau font, menambah border atau pun juga shadow .</p>
<p>Namun dalam pembelajaran pemrograman web terkadang kurang saya merasa sulit untuk mengerti atau memahami dari pembelajaran yang sudah diterangkan didepan karena belum dimengerti atau dipahami secara baik dan kadang pula harus mendownload terlebih dahulu aplikasinya tapi di kelas tempat yang digunakan itu tidak memiliki atau bermasalah dengan koneksi yang ada di kampus jadi harus menunggu dari orang lain yang download atau minta di pak.</p>
<p>Saat awal pembelajarannya juga saya merasa sulit tapi lama kelamaan mengikuti PWEB saya pelan-pelan untuk mencoba mencari tahu apa yang harus diperbaiki atau yang ditambahkan untuk membuat halaman web tersebut sesuai dengan yang diinginkan pak dengan sesuai kemampuan saya. </p>
<p>Kadang pak sofyan juga memberikan tugas yang rumit,banyak dan sulit karena saya tidak bisa menyelesaikan tersebut dengan cepat hingga saya merasa bahwa tugas yang dikerjakan harus tugas pweb karena harus selesai kemudian baru saya akan mengerjakan tugas yang lain tapi saya sudah mencoba untuk membuat dan mengerjakan tugas tersebut sesuai dengan contoh atau ketentuan yang sudah diperlihatkan atau yang diberikan dari pak.</p>
<p>Tugas yang diberikan dari pak kalau saya yang mengerjakan tugasnya bisa berhari-hari bahkan sebelum hari h baru selesai dan setelah itu dikirim ke github dan pada saat hari h nya atau saat hari pembelajaran pemrograman web biasanya akan diberi score tapi selama saya mengikuti pembelajaran ini sepertinya score yang saya dapatkan tidak pernah lebih dari 30 maka dari itupun ada rasa kecewa tapi itulah hasil kerja saya dan yang penting saya sudah mengerjakan tugas tersebut yang diberikan dengan sebaik mungkin dan sesuai kemampuan saya.</p>
<p>Tapi selama yang diajarkan pak sofyan saya dapat mengerti dengan baik cuma kadang saya lupa dan kurang memahami yang sudah diterangkan sehingga terkadang saya harus menanyakan kepada teman sekelas yang lebih mengerti atau teman yang tau tentang apa yang sudah diterangkan oleh pak. 
<p>Dan kadang terasa saat kelas pweb ada juga yang lucu karena biasanya saat pak sedang menerangkan tiba-tiba ada yang masih mengetik atau mengklik mousenya dan pak juga diam sehingga menunggu bunyi-buni tersebut betul-betul tidak ada sehingga harus menunggu bunyi tersebut betul-betul tidak ada kemudian pak akan melanjutkan yang diterangkan . Menurut saya cara itu juga sebenarnya untuk mendisiplinkan kami agar lebih menghargai dosen yang sedang ada di depan. </p>
